### ISSUE TITLE
NerdQAxe++ build guide

### ISSUE THREAD

**Issue by invisibleecho** [shufps/qaxe#14]
Hello,

I was about to order an avalon nano 3, but 4TH/s @ 140Watts is not too efficient. I saw bitaxe gamma at 1.2TH/s @ 15Watts which is impressive but expensive for like 229€ each unit.

Im aiming to get an efficient home miner which gets good speed like 8TH/s under 200 Watts and your project looks insane!

Are there any tutorials on how to build this yourself? Do you have a list of parts and where to get the correct parts or something like this?

I need one of those! :)

Thanks for your awesome work!

Best regards

**Comment by shufps** [comment]
Hi, 

thank you a lot for your interest in this project :hugs: 

> Are there any tutorials on how to build this yourself? Do you have a list of parts and where to get the correct parts or something like this?

Hmm, to be honest, the complexity of such miner is on "pro-level" and even people with skills obtained over decades struggle with it.

So I guess there is no tutorial how to do it - if you have the skills required the information from this repository are enough (the project has been completed by several people already - with maybe a little help in the OSMU Discord channel). :speak_no_evil: 

Yes, there is a list of parts called BOM (bill of material). This are csv lists that can be imported into Digikey for ordering.

Best regards
