### ISSUE TITLE
embassy @ 9cd0bea Question

### ISSUE THREAD

**Issue by lv333ming** [shufps/qaxe#6]
What does this file embassy @ 9cd0bea do?  I'm a newbie and don't quite understand。

**Comment by shufps** [comment]
Embassy-rs is quite a new project that has not stabilized yet. It's added to the repository as submodule with a fixed commit hash, so the firmware compiles even if there are breaking changes in the main branch of embassy.

So it ties the version of embassy to the repository, so to say :slightly_smiling_face:
